Repository sparrowapp-dev/sparrow-app-auth, pull requests merged in 2025-07, with the labels that each got.

#170 Release Version 2.27.0 [Merging development into prod]
  .env.example
  src/lib/components/bgContainer/BgContainer.svelte
  src/lib/components/tabs/Tabs.svelte
  src/lib/store/bgContainerHeight.ts
  src/pages/Auth/entry-point/EntryPoint.svelte
  src/pages/Auth/redirect/Redirect.svelte
  src/pages/Auth/verify-magic-code/VerifyMagicCode.svelte
Labels: released

#172 feat: Trial flow [SPRW-1361]
  src/lib/services/auth.service.ts
  src/pages/Auth/entry-point/EntryPoint.svelte
  src/pages/Auth/login-page/LoginPage.svelte
  src/pages/Auth/register-page/RegisterPage.svelte
  src/pages/Auth/register-page/register-page.ts
Labels: feature

#175 patch: patch release for admin panel
  src/lib/services/auth.service.ts
  src/pages/Auth/entry-point/EntryPoint.svelte
  src/pages/Auth/login-page/LoginPage.svelte
  src/pages/Auth/register-page/RegisterPage.svelte
  src/pages/Auth/register-page/register-page.ts
Labels: released

#176 Add plan page for different trials [SPRW-1454].
  .env.example
  src/App.svelte
  src/global.d.ts
  src/lib/assets/CheckIcon.svelte
  src/lib/components/button/Button.svelte
  src/lib/components/tags/Tags.svelte
  src/lib/utils/constants.ts
  src/pages/Auth/plans/Plans.svelte
  src/pages/Auth/plans/components/pricing-card/PricingCard.svelte
  src/pages/Auth/verify-email/VerifyEmail.svelte
Labels: feature

#180 feat: added marketing site env []
  .github/workflows/development.yml
  .github/workflows/main.yml
Labels: feature

#188 fix: updated the email validation regex [SPRW-991]
  src/lib/utils/validation.ts
Labels: bug
