Repository sparrowapp-dev/sparrow-app-auth, pull requests merged in 2025-01, with the labels that each got.

#107 feat/added-app-route-comments
  src/App.svelte
Labels: documentation

#116 Release Version 2.15.0 [Merging development into prod]
  src/App.svelte
  src/lib/utils/validation.ts
  src/pages/Auth/cool-down-page/CoolDownPage.svelte
  src/pages/Auth/entry-point/EntryPoint.svelte
  src/pages/Auth/login-page/LoginPage.svelte
  src/pages/Auth/oauth-redirect/OauthRedirect.svelte
  src/pages/Auth/redirect/RegisterRedirectComponent.svelte
  src/pages/Auth/verify-magic-code/VerifyMagicCode.svelte
Labels: released

#122 Users name is missing in send magic code state #2278
  src/App.svelte
  src/pages/Auth/entry-point/EntryPoint.svelte
  src/pages/Auth/verify-magic-code/VerifyMagicCode.svelte
Labels: bug

#126 One intermediate screen is present in dev after login, which is not present in figma (present in all the login and sign-up options) #2385
  src/pages/Auth/oauth-redirect/OauthRedirect.svelte
Labels: bug

#125 sign up issues if user enters enter multiple spaces in first name #2358
  src/lib/utils/validation.ts
Labels: bug

#132 Release Version 2.16.0 [Merging development into prod]
  src/App.svelte
  src/lib/utils/validation.ts
  src/pages/Auth/entry-point/EntryPoint.svelte
  src/pages/Auth/login-page/LoginPage.svelte
  src/pages/Auth/verify-magic-code/VerifyMagicCode.svelte
Labels: released
